enabled: true
footer_icons:
  -
    icon: fa-facebook
    url: 'https://www.facebook.com/UofSCSSS/'
  -
    icon: fa-instagram
    url: 'https://www.instagram.com/csss_usask/'
  -
    icon: fa-twitter
    url: 'https://www.twitter.com/'
  -
    icon: fa-linkedin
    url: 'https://ca.linkedin.com/company/computer-science-student-society'
footer_blocks:
  -
    title: null
    content: 'Continually matrix cross functional opportunities whereas ethical information. Compellingly streamline enabled human capital before resource-leveling internal or "organic".'
    logo: true
    icons: false
  -
    title: 'We work for your profit'
    content: 'Distinctively expedite viral materials rather than out-of-the-box solutions. Credibly empower revolutionary ROI rather than unique products. Collaboratively maximize principle-centered ideas before highly efficient data. Phosfluorescently.'
    logo: false
    icons: false
  -
    title: 'Join Us'
    content: "Call Us 666 777 888 OR 111 222 333\n\nSend an Email on <a href=\"mailto:#\">contact@domain.com</a>\n\nVisit Us 123 Fake Street- Blla 12358\nFake Kingdom"
    logo: false
    icons: true
copyright: null
google_maps_api_key: null
favicon:
  user/themes/x-corporation/img/csss_logo.png:
    name: csss_logo.png
    full_path: csss_logo.png
    type: image/png
    size: 221847
    path: user/themes/x-corporation/img/csss_logo.png
logo: {  }
